version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.1
workflows:
  build:
    jobs:
      - cypress/run:
          start-command: 'npm run test'
          cypress-command: 'npx cypress run'

    steps:
      - store_artifacts:
          path: /home/circleci/project/cypress/videos

      - store_test_results:
          path: /home/circleci/project/results